### ISSUE TITLE
Why lock page twice

### ISSUE THREAD

**Issue by BlackLuny** [changeofpace/VivienneVMM#13]
https://github.com/changeofpace/VivienneVMM/blob/537bd8dfa3a4f42ed6baa7f1c5c1a2799a95e0a2/VivienneVMM/ept_breakpoint_manager.cpp#L3906

If user specified keep page resident,locked the pages by MmProbeAndLockPages, But I am confused why called MmProbeAndLockPages twice in EbmpCreateLockedPageEntry function.

**Comment by changeofpace** [comment]
The `fMakePageResident` parameter exists because processes can use "trap pages" to detect if remote processes are tampering with the host process's memory. A process can allocate a page of memory, force it to be paged out, and then constantly query whether it's paged in or not. If this trap page is ever resident then the process knows that a remote process or an unexpected dll has touched it. By specifying FALSE for `fMakePageResident` the VMM does not cause this measurable side effect in the target process.

The `EbmpCreateLockedPageEntry` function is awkward code because the locked page list is keyed by the base address of the physical page. The first call to `MmProbeAndLockPages` allows us to always get the backing physical page (assuming the target virtual address is valid) which we need to query if a locked page entry already exists. If there is no locked page entry then we call `MmProbeAndLockPages` a second time to lock the page while it has active breakpoints. I thought that this was the simplest solution, but maybe it's better to have two separate `EbmpCreateLockedPageEntry` functions depending on whether the user wants to make the page resident or not.
