### ISSUE TITLE
About taking sample

### ISSUE THREAD

**Issue by progmboy** [changeofpace/VivienneVMM#3]
I noticed that in the project, After VMM capturing the debug event, the data is obtained by timed sampling. And my question is why you don't use real-time interprocess communication (just like the debugging mechanism of Windows uses DebugPort) to let the user process get the real-time data. ?

**Comment by changeofpace** [comment]
I use timed sampling for the capture execution context commands so that they can be used via a single `METHOD_BUFFERED` ioctl. I chose this technique because it was simple to implement and understand.

I agree that real-time communication is a better solution. I will research how debug ports are implemented to see how that method compares to other techniques (e.g., shared memory).

My goal with implementing an improved communications method would be to make the driver interface capable of being consumed by user mode debuggers like x64dbg and cheat engine.

**Comment by changeofpace** [comment]
The ept breakpoint manager introduced in the 1.0.0 releases uses mapped section views to store breakpoint logs.
